name = "Glim Midnight"
description = "A minimal links page made with Hugo"

license = "MIT"
licenselink = "https://github.com/mansoorbarri/glim-midnight/blob/master/LICENSE"

homepage = "https://github.com/mansoorbarri/glim-midnight/"
demosite = "http://glim-midnight.mansoorbarri.com/"

tags = ["Bootstrap", "Dark", "Minimal", "Responsive"]
min_version = "0.133.0"

authors = [
  {name = "Mansoor Barri", homepage = "https://mansoorbarri.com"},
] 